export enum GeneralErrors {
  API_SERVER_DOWN = 'API_SERVER_DOWN',
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
  OBJECT_NOT_FOUND_IN_DATABASE = 'OBJECT_NOT_FOUND_IN_DATABASE',
}
