export enum GeneralErrors {
  API_SERVER_DOWN = "API_SERVER_DOWN",
  UNHANDLED_ERROR = "UNHANDLED_ERROR",
  MUST_MYSL_ACTIVE = "MUST_MYSL_ACTIVE",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  OBJECT_NOT_FOUND_IN_DATABASE = "OBJECT_NOT_FOUND_IN_DATABASE",
}

export enum ClientErrors {
  AXIOS_NO_RESPONSE = "AXIOS_NO_RESPONSE",
  BACKEND_ERROR = "BACKEND_ERROR",
  BACKEND_NOT_RESPONDING = "BACKEND_NOT_RESPONDING",
  BACKEND_GENERAL_ERROR = "BACKEND_GENERAL_ERROR",
  PROXY_UNKNOWN_ERROR = "PROXY_UNKNOWN_ERROR",
}

export enum WsErrors {
  WS_NO_RESPONSE = "WS_NO_RESPONSE",
  WS_JWT_TOKEN = "WS_JWT_TOKEN",
}

export enum UserErrors {
  USER_LOGIN_EXIST = "USER_LOGIN_EXIST",
  USER_EMAIL_EXIST = "USER_EMAIL_EXIST",
}

export enum AuthenticationErrors {
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_BLOCKED = "AUTH_BLOCKED",
  AUTH_MUST_BE_LOGGED_OFF = "AUTH_MUST_BE_LOGGED_OFF",
  AUTH_NO_TOKEN_PROVIDED = "AUTH_NO_TOKEN_PROVIDED",
  AUTH_TOKEN_IS_NOT_AUTHENTIC = "AUTH_TOKEN_IS_NOT_AUTHENTIC",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_NO_ROLE_ALLOWED = "AUTH_NO_ROLE_ALLOWED",
  AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED = "AUTH_ACCESS_TO_INTRANET_NOT_ALLOWED",
  AUTH_DISABLED_ACCOUNT = "AUTH_DISABLED_ACCOUNT",
  ACCESS_NOT_AUTHORIZED = "ACCESS_NOT_AUTHORIZED",
}
